/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package extratuitioncenter;

import static extratuitioncenter.RecordOfStudentGUI.LogInValue;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hussain
 */
public class AttendanceClassGUI extends javax.swing.JFrame {
    DefaultTableModel mdl = new DefaultTableModel();
    Connection connct = null;
    ResultSet rslt = null;
    PreparedStatement state = null;
    /**
     * Creates new form AttendClassGui
     * @throws java.sql.SQLException
     */
    public AttendanceClassGUI() throws SQLException {
        initComponents();
        attendLesson.setEnabled(false);
        missedLesson.setEnabled(false);
        getConnect();
        Object columns[] = {"LessonID", "StudentID", "LessonSubject", "LessonStatus", "LessonDate", "LessonTime", "RoomNo"};
        mdl.setColumnIdentifiers(columns);
        studentBookedLessonsTable.setModel(mdl);
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentBookedLessonsTable = new javax.swing.JTable();
        studentID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        attendLesson = new javax.swing.JButton();
        missedLesson = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        enteredProgress = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BookNameComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(144, 123, 242));

        studentBookedLessonsTable.setBackground(java.awt.Color.lightGray);
        studentBookedLessonsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(studentBookedLessonsTable);

        studentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Please Enter Student ID:");

        attendLesson.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        attendLesson.setText("Attended");
        attendLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendLessonActionPerformed(evt);
            }
        });

        missedLesson.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        missedLesson.setText("Missed");
        missedLesson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                missedLessonActionPerformed(evt);
            }
        });

        enteredProgress.setColumns(20);
        enteredProgress.setRows(5);
        jScrollPane2.setViewportView(enteredProgress);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Please Enter Student Progress:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Suggession of Book (Optional)");

        jButton1.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jButton1.setText("<Previous Page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BookNameComboBox.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        BookNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English comprehension", "English writing", "Math", "Numerical Reasoning", "Verbal Reasoning", "Non-verbal Reasoning" }));
        BookNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookNameComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel1)
                .addGap(90, 90, 90)
                .addComponent(studentID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(BookNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(attendLesson)
                    .addComponent(missedLesson, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(312, 312, 312))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(attendLesson)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(missedLesson))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(BookNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDActionPerformed
        try {
            // TODO add your handling code here:
            loadData();
            attendLesson.setEnabled(true);
       
        missedLesson.setEnabled(true);
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_studentIDActionPerformed

    private void missedLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_missedLessonActionPerformed
        // TODO add your handling code here:
        try {
            int slctdRowIndx = studentBookedLessonsTable.getSelectedRow();
            String lesson_ID = mdl.getValueAt(slctdRowIndx, 0).toString();
            String sql = "UPDATE LESSON SET StudentID = ' ',LessonStatus= 'Available' WHERE LessonID='" + lesson_ID + "'";
            state = connct.prepareStatement(sql);
            state.executeUpdate();
             String TeacherID = RecordOfStudentGUI.LogInValue;
                     String StdID = mdl.getValueAt(slctdRowIndx, 1).toString();
               String LessonSub = mdl.getValueAt(slctdRowIndx, 2).toString();
                String LessonStats = mdl.getValueAt(slctdRowIndx, 3).toString();
                 String DateLesson = mdl.getValueAt(slctdRowIndx, 4).toString();
                  String LesonTime = mdl.getValueAt(slctdRowIndx, 5).toString();
                  String RmNu = mdl.getValueAt(slctdRowIndx, 6).toString();
            String sql1="INSERT INTO LESSONPROGRESS (LessonID,TeacherID,StudentID,Subject,LessonDate,LessonTime,AttendanceStatus,RoomNo,StudentProgress) VALUES ('"+lesson_ID+"','"+TeacherID+"','"+StdID+"','"+LessonSub+"','"+DateLesson+"','"+LesonTime+"','Missed','"+RmNu+"','Lesson not attended')";
            state=connct.prepareStatement(sql1);
            state.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated" + LogInValue + lesson_ID);
            attendLesson.setEnabled(false);
            mdl.setRowCount(0);
            loadData();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
           
           
        }
        
    }//GEN-LAST:event_missedLessonActionPerformed

    private void attendLessonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendLessonActionPerformed
        // TODO add your handling code here:
        
         try {
            int slctedRowindx = studentBookedLessonsTable.getSelectedRow();
            String lesson_ID = mdl.getValueAt(slctedRowindx, 0).toString();
            String sql = "UPDATE LESSON SET StudentID = ' ',LessonStatus= 'Available' WHERE LessonID='" + lesson_ID + "'";
            state = connct.prepareStatement(sql);
            state.executeUpdate();
             String TecID = RecordOfStudentGUI.LogInValue;
                     String StdID = mdl.getValueAt(slctedRowindx, 1).toString();
               String LesonSub = mdl.getValueAt(slctedRowindx, 2).toString();
                String LesonSubjct = mdl.getValueAt(slctedRowindx, 3).toString();
                 String LesonDate = mdl.getValueAt(slctedRowindx, 4).toString();
                  String LesonTime = mdl.getValueAt(slctedRowindx, 5).toString();
                  String RmNu = mdl.getValueAt(slctedRowindx, 6).toString();
                  String StdPrgrs= enteredProgress.getText();
            String sql1="INSERT INTO LESSONPROGRESS (LessonID,TeacherID,StudentID,Subject,LessonDate,LessonTime,AttendanceStatus,RoomNo,StudentProgress) VALUES ('"+lesson_ID+"','"+TecID+"','"+StdID+"','"+LesonSub+"','"+LesonDate+"','"+LesonTime+"','Attended','"+RmNu+"','"+StdPrgrs+"')";
            state=connct.prepareStatement(sql1);
            state.executeUpdate();
            String sql2="INSERT INTO BOOK(BookName,StudentID) VALUES ('"+BookNameComboBox.getSelectedItem()+"','"+StdID+"')";
            state = connct.prepareStatement(sql2);
            state.executeUpdate();
            missedLesson.setEnabled(false);
            mdl.setRowCount(0);
            loadData();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
        
    }//GEN-LAST:event_attendLessonActionPerformed

    private void BookNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookNameComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookNameComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainMenuTeacherGUI s= new MainMenuTeacherGUI();
         s.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                s.setSize(800, 600);
                s.setLocationRelativeTo(null);
                s.setVisible(true);
                this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendanceClassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendanceClassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendanceClassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendanceClassGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new AttendanceClassGUI().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(AttendanceClassGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

     private void getConnect() throws SQLException {
         String url = "jdbc:sqlite:extraTuitionCentre";

        // create a connctn to the database

        connct = DriverManager.getConnection(url);
    }
 public void loadData() throws SQLException {
      
        System.out.println("Connection to SQLite has been established.");
        String sql = "Select LessonID,StudentID,LessonSubject,LessonStatus,LessonDate,LessonTime,RoomNo from LESSON where TeacherID='"+RecordOfStudentGUI.LogInValue+"' AND LessonStatus = 'Booked' AND StudentID='"+studentID.getText()+ "'";
        try {
            state = connct.prepareStatement(sql);
            rslt = state.executeQuery();
            Object[] columnData = new Object[7];
            while (rslt.next()) {
                columnData[0] = rslt.getString("LessonID");
                columnData[1] = rslt.getString("StudentID");
                columnData[2] = rslt.getString("LessonSubject");
                columnData[3] = rslt.getString("LessonStatus");
                columnData[4] = rslt.getString("LessonDate");
                columnData[5] = rslt.getString("LessonTime");
                columnData[6] = rslt.getString("RoomNo");

                mdl.addRow(columnData);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BookNameComboBox;
    private javax.swing.JButton attendLesson;
    private javax.swing.JTextArea enteredProgress;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton missedLesson;
    private javax.swing.JTable studentBookedLessonsTable;
    private javax.swing.JTextField studentID;
    // End of variables declaration//GEN-END:variables
}
