/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package extratuitioncenter;

import static extratuitioncenter.RecordOfStudentGUI.LogInValue;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hussain
 */
public class LessonCancelGUI extends javax.swing.JFrame {
 DefaultTableModel mdl = new DefaultTableModel();
    Connection connctn = null;
    ResultSet rslt = null;
    PreparedStatement prState = null;
    RecordOfStudentGUI sss;
    /**
     * Creates new form cancleLessonGUI
     * @throws java.sql.SQLException
     */
    public LessonCancelGUI() throws SQLException {
        initComponents();
     try {
         sss= new RecordOfStudentGUI();
         getConnect();
     }
     catch (SQLException ex) {
         JOptionPane.showMessageDialog(null, ex);
     }
       
        Object columns[] = {"LessonID", "TeacherID", "LessonSubject", "LessonStatus", "LessonDate", "LessonTime", "RoomNo"};
        mdl.setColumnIdentifiers(columns);
        LessonBookingTable.setModel(mdl);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LessonBookingTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(144, 123, 242));

        LessonBookingTable.setBackground(java.awt.Color.lightGray);
        LessonBookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(LessonBookingTable);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Cancle Booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jButton2.setText("<Previous Page");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(317, 317, 317))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
             
        try {
            int SelectedRowIndex = LessonBookingTable.getSelectedRow();
            String lessonID = mdl.getValueAt(SelectedRowIndex, 0).toString();
            String sql = "UPDATE LESSON SET StudentID = ' ',LessonStatus= 'Available' WHERE LessonID='" + lessonID + "'";
            prState = connctn.prepareStatement(sql);
            prState.executeUpdate();
            String stdID = RecordOfStudentGUI.LogInValue;
                     String TecID = mdl.getValueAt(SelectedRowIndex, 1).toString();
               String LesonSub = mdl.getValueAt(SelectedRowIndex, 2).toString();
                String LesonStats = mdl.getValueAt(SelectedRowIndex, 3).toString();
                 String LesonDate = mdl.getValueAt(SelectedRowIndex, 4).toString();
                  String LesonTime = mdl.getValueAt(SelectedRowIndex, 5).toString();
                  String RmNu = mdl.getValueAt(SelectedRowIndex, 6).toString();
            String sql1="INSERT INTO LESSONPROGRESS (LessonID,TeacherID,StudentID,Subject,LessonDate,LessonTime,AttendanceStatus,RoomNo,StudentProgress) VALUES ('"+lessonID+"','"+TecID+"','"+stdID+"','"+LesonSub+"','"+LesonDate+"','"+LesonTime+"','Canceled','"+RmNu+"','Lesson canceled by student')";
            prState=connctn.prepareStatement(sql1);
            prState.executeUpdate();
            mdl.setRowCount(0);
            loadData();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
            
            
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        MainMenuStudentGUI s= new MainMenuStudentGUI();
         s.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                s.setSize(800, 600);
                s.setLocationRelativeTo(null);
                s.setVisible(true);
                this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new LessonCancelGUI().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(LessonCancelGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }
    
    private void loadData() throws SQLException {
        
        String sql = "Select LessonID,TeacherID,LessonSubject,LessonStatus,LessonDate,LessonTime,RoomNo from LESSON where StudentID= '"+RecordOfStudentGUI.LogInValue+"' AND  LessonStatus = 'Booked'";
        try {
            prState = connctn.prepareStatement(sql);
            rslt = prState.executeQuery();
            Object[] columnData = new Object[7];
            while (rslt.next()) {
                columnData[0] = rslt.getString("LessonID");
                columnData[1] = rslt.getString("TeacherID");
                columnData[2] = rslt.getString("LessonSubject");
                columnData[3] = rslt.getString("LessonStatus");
                columnData[4] = rslt.getString("LessonDate");
                columnData[5] = rslt.getString("LessonTime");
                columnData[6] = rslt.getString("RoomNo");

                mdl.addRow(columnData);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
    
  private void getConnect() throws SQLException {
        String url = "jdbc:sqlite:extraTuitionCentre";

        // create a connctn to the database

        connctn = DriverManager.getConnection(url);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable LessonBookingTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
